version: '3'

services:
    web:
#        build:
#            context: .
#            dockerfile: Dockerfile
        image: flask_diagram
        container_name: flask_diagram_app
        ports:
            - "8080:8080"
        volumes:
            - ./models:/home/appuser/models/
        command: bash -c "python app.py"
        env_file:
          - .env
